endpoints:
  shutdown:
    enabled: true
    sensitive: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
management:
  security:
    enabled: false
server:
  port: 9000
spring:
  application:
    name: ribbon-consumer
    
