eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka
logging:
  level:
    cn:
      com:
        clumsybear:
          service:
            HelloService: FULL
server:
  port: 9001
spring:
  application:
    name: feign-consumer
