eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
logging:
  level:
    org:
      springframework: info
      
      
email-configs:
  mail:
    swxt:
      host:
        10.8.19.145
      user:
        xinxi_vms_admin
      protocol:
        smtp
      auth:
        true
    fybx:
      host:
        10.8.19.145
      user:
        xinxi_bx_admin
      protocol:
        smtp
      auth:
        true
  
