eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    #serviceUrl:
    #  defaultZone: http://localhost:7001/eureka/
  instance:
    hostname: localhost

server:
  port: 1111
