server:
  port: 7001
spring:
  application:
    name: config-server

    
  cloud:
    config:
      server:
        git:
          uri: 
            https://github.com/jiangzhangpeng/spring-cloud-learning/
          search-paths:
            config-repo
          username: 
            jiangzp_beijing@163.com
          password:
            Geiwo100kuaiqian

#security:#  user:#    name: 
#      user
#    password:
#      123456abc
      
encrypt:  key:
    chongxing

#logging.level.org.springframework: debug

eureka:  client:    service-url:      defaultZone: http://localhost:1111/eureka/
